import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import AdvertHeader from '../components/layout/AdvertHeader';
import Navbar from "@/components/layout/Navbar";

const poppins = localFont({
  src: [
    {
      path: '../assets/fonts/Poppins-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Poppins-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Poppins-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Poppins-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-poppins',
});

const inter = localFont({
  src: [
    {
      path: '../assets/fonts/Inter-Variable.ttf',
      style: 'normal',
      weight: '500'
    }
  ],
  variable: '--font-inter'
});

const plusjakarta = localFont({
  src: [
    {
    path: '../assets/fonts/PlusJakartaSans-Variable.ttf',
    style: 'normal',
    weight: '400'
    }
  ],
  variable: '--font-jakarta'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${plusjakarta.variable} ${poppins.variable} antialiased`}
    >
      <body className="">
        <header className="sticky top-0 z-20 backdrop-blur-sm">
          <AdvertHeader/>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
